### ISSUE TITLE
How to count combinations of the total alignments

### ISSUE THREAD

**Issue by zhiqwang** [distillpub/post--ctc#36]
Thanks for this excellent explanation of CTC Loss, In the Footnotes section, I notice:

> For a Y of length U without any repeat characters and an X of length T the size of the set is {T+U \choose T-U}

I compute this formula in following:

First, suppose the sequence only have non-blank character, the sequence's length ranges from U to T, then we patch the blank token to the sequence to have length T, the result is in the left of below equation:

![image](https://user-images.githubusercontent.com/4210061/56089328-d4014f00-5ec3-11e9-9916-76e191ecf32c.png)

and I numerically verify the equality of the equation.

I don't know is there a straightforward explanation of equation {T+U \choose T-U}?

**Comment by awni** [comment]
Use the "stars and bars theorem" (the second theorem here - https://en.wikipedia.org/wiki/Stars_and_bars_(combinatorics)).

To reduce the number of alignments to the theorem we have:

1. T frames of which U are already accounted for since each character must align somewhere. So we have T-U "stars".
2. We have 2U + 1 "bars" since we have an epsilon for each character and then one additional epsilon.

Then just insert those numbers into the equation.

**Comment by zhiqwang** [comment]
It's cool, thanks for your sharing.
